### ISSUE TITLE
Does not seem to work on lambda

### ISSUE THREAD

**Issue by repl-chris** [tristanls/dynamodb-lock-client#2]
If I try to use this library on lambda I get this error, although if I load it locally in node 6.10.3 it seems to be fine.

Unable to import module 'main_index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/joi/lib/index.js:6:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by tristanls** [comment]
Hi @repl-chris ,

I haven't attempted to use this module on AWS Lambda so I'm unsure what the issue might be. Looking at the stack trace you posted I don't see anything specific to `dynamodb-lock-client`. Do you have a full example of the AWS Lambda you're trying to run, or perhaps a minimal AWS Lambda function that can reproduce the error you're getting?

**Comment by repl-chris** [comment]
Hmmmmm yeah just trying to do a minimal repro here and it's working fine on lambda.  I'm not sure what's going on, I have a larger app that as soon as I add the reference it starts failing with that error.  It must somehow be conflicting with another module I have installed or something.  Sorry for the false report, I'll close this until I have a little more time to dig into what is actually happening.

**Comment by tristanls** [comment]
No worries. Sorry to hear the module is causing problems. 

I can think of two things, which you may already have considered, or which may have nothing to do with the problem... two shots in the dark, if you will :).

Based on the stack trace, the only thing I can think of is that maybe `Joi` versions don't match for some reason? `at Object. (/var/task/node_modules/joi/lib/index.js:6:13)` was updated on May 1 around 10.5.0 release some time.

The other thing would be that `dynamodb-lock-client` requires `aws-sdk` as a `devDependency`. I noticed, in the past, that AWS Lambda really does not like (crashes) if I upload my own `aws-sdk` in `node_modules`. So, maybe if `npm install` instead of `npm install --production` is used, somehow `dynamodb-lock-client` includes `aws-sdk` and that breaks things. I'd expect a different stack trace, but... just guessing here.

On another note, I'll be putting this module in my own AWS Lambda in the near future, so maybe I'll reproduce.
