### ISSUE TITLE
Recordings changed from 0.6.1 to 0.6.2

### ISSUE THREAD

**Issue by simlu** [tristanls/dynamodb-lock-client#23]
Our recordings changed when updating dynamodb-lock-client. From the changelog it is not clear why that happens:

https://github.com/blackflux/dy-alchemy/pull/958/files

It looks like when the lock is released, it no longer just looks at the id, but at everything else as well.

Would be very grateful if you could elaborate @tristanls ! Cheers!

**Comment by tristanls** [comment]
At first glance it appears to be the consequence of this change: https://github.com/tristanls/dynamodb-lock-client/commit/96c28a6dfbb907f6b18af0c53ad53a2af5f5ef66#diff-168726dbe96b3ce427e7fedce31bb0bcR406 .

Based on the change you've recorded, it would seem to me that in that recording you were creating a `FailOpen` lock without specifying `heartbeatPeriodMs`. Notice (in the change I highlighted), that it determines whether to execute `FailOpen` or `FailClosed` `release` protocol based on the presence of `self._heartbeatTimeout`. `self._heartbeatTimeout` is never set if `heartbeatPeriodMs` is not specified on `FailOpen` lock construction. 

Change from `0.6.1` to `0.6.2` fixes the bug of using the wrong `release` protocol. Previously, if you didn't specify `heartbeatPeriodMs` when creating `FailOpen` lock, the `release` protocol for a `FailClosed` lock was being executed (a straightforward delete without checking lock state, which is why you're seeing only `Key.id.lock-name`). Now, correctly, the `FailOpen` `release` protocol is being executed, which does a conditional update instead of delete, which is why you're seeing `Item` in the recording, with accompanying data.

You should only be seeing difference in recordings for `FailOpen` locks created without specifying `heartbeatPeriodMs`.

**Comment by simlu** [comment]
Hello @tristanls ! As always, thank you very much for the detailed explanation! That all makes sense, let's hope it doesn't cause any issues for us :crossed_fingers:
