### ISSUE TITLE
Are you using this in production?

### ISSUE THREAD

**Issue by simlu** [tristanls/dynamodb-lock-client#4]
Considering that there are no tests... Are you using this? How tested is this implementation?

**Comment by Jacob-Lynch** [comment]
Hey, I've been using this on our production lambdas since late last year when @tristanls fixed the only issue I've run into so far.  In the last three months the lambdas have been called 30k+ times with no issues that I've noticed.  We use it to prevent duplicate objects being created in our database.

**Comment by simlu** [comment]
Thank you both for the feedback! 

@Jacob-Lynch We got quite similar use cases then. Our load might be significantly bigger though. Let's see how well it holds up!

**Comment by simlu** [comment]
Works well. Thanks for the feedback!

We'll be stress testing more down the road, but will open ticket if we run into issues.

Closing

**Comment by tristanls** [comment]
Thank you for circling back and letting us know! :)
